version: "3.9"

services:
  frontend:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true   # Keep STDIN open for interactive processes
    tty: true          # Allocate a pseudo-TTY

  backend:
    build:
      context: ./backend
    ports:
    - "8080:8080"
    # volumes:
    #   - .:/backend
    
  elasticsearch:
      image: elasticsearch:7.8.1
      platform: linux/x86_64
      ports:
        - 9200:9200
      environment:
        discovery.type: 'single-node'
        xpack.security.enabled: 'true'
        ELASTIC_PASSWORD: '<your_password>'
        ES_JAVA_OPTS: '-Xmx2g -Xms2g'
  kibana:
      image: kibana:7.8.1
      platform: linux/x86_64
      volumes:
        - ./kibana.yml:/usr/share/kibana/config/kibana.yml
      ports:
        - 5601:5601